name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup Amplify Configuration
        run: |
          echo '${{ secrets.AMPLIFY_CONFIGURATION }}' > src/amplifyconfiguration.json
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test
