name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Amplify Configuration
        run: |
          echo '${{ secrets.AMPLIFY_CONFIGURATION }}' > src/amplifyconfiguration.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

      - name: Run unit tests
        run: npm run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: comp4350teamsaffron/neighbourhood:latest

      - name: Pull the Docker image from Docker Hub
        run: docker pull comp4350teamsaffron/neighbourhood:latest

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Tag the Docker image for Heroku
        run: docker tag comp4350teamsaffron/neighbourhood:latest registry.heroku.com/neighbourhood/web

      - name: Push the Docker image to Heroku Container Registry
        run: docker push registry.heroku.com/neighbourhood/web

      - name: Release the Docker image to the Heroku app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku container:release web --app ${HEROKU_APP_NAME}
